name: Daily Alfa Romeo Feed Update to Gist

on:
  schedule:
    - cron: '0 2 * * *'  # 3:00 rano czasu polskiego
  workflow_dispatch:     # Pozwala uruchomić ręcznie

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Scraper
        run: python alfa_romeo_inventory_scraper.py

      - name: Update Gist
        uses: exuanbo/gist-actions@v2
        with:
          gist_id: 4d86df02798a5e87c6cdb7b358904717
          gist_token: ${{ secrets.GIST_TOKEN }}
          file_path: alfa_romeo_inventory.csv